[package]
name = "luce_pkg_server"
source = "src"

[exports]
registry = "luce_pkg_server.registry"
repositories = "luce_pkg_server.repositories"

[dependencies]
luce_server = "../luce-server"
luce_db = "../luce-db"
luce_auth = "../luce-auth"
luce_json = "../luce-json"
luce_prism = "../luce-prism"
luce_git = "../luce-git"
